# Generated by Django 4.0 on 2021-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
