# Generated by Django 4.0 on 2021-12-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_rename_stajirovka_team_experience_alter_team_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='biography',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
